// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	models "github.com/runtime-metrics-course/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// StorageIface is an autogenerated mock type for the StorageIface type
type StorageIface struct {
	mock.Mock
}

// GetMetrics provides a mock function with no fields
func (_m *StorageIface) GetMetrics() models.Metrics {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 models.Metrics
	if rf, ok := ret.Get(0).(func() models.Metrics); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Metrics)
	}

	return r0
}

// Ping provides a mock function with no fields
func (_m *StorageIface) Ping() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCounter provides a mock function with given fields: name, value
func (_m *StorageIface) UpdateCounter(name string, value int64) {
	_m.Called(name, value)
}

// UpdateGauge provides a mock function with given fields: name, value
func (_m *StorageIface) UpdateGauge(name string, value float64) {
	_m.Called(name, value)
}

// NewStorageIface creates a new instance of StorageIface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageIface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageIface {
	mock := &StorageIface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
