// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StorageIface is an autogenerated mock type for the StorageIface type
type StorageIface struct {
	mock.Mock
}

// GetCounters provides a mock function with given fields:
func (_m *StorageIface) GetCounters() map[string]int64 {
	ret := _m.Called()

	var r0 map[string]int64
	if rf, ok := ret.Get(0).(func() map[string]int64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	return r0
}

// GetGauges provides a mock function with given fields:
func (_m *StorageIface) GetGauges() map[string]float64 {
	ret := _m.Called()

	var r0 map[string]float64
	if rf, ok := ret.Get(0).(func() map[string]float64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}

	return r0
}

// PrintMetrics provides a mock function with given fields:
func (_m *StorageIface) PrintMetrics() {
	_m.Called()
}

// UpdateCounter provides a mock function with given fields: name, value
func (_m *StorageIface) UpdateCounter(name string, value int64) {
	_m.Called(name, value)
}

// UpdateGauge provides a mock function with given fields: name, value
func (_m *StorageIface) UpdateGauge(name string, value float64) {
	_m.Called(name, value)
}

type mockConstructorTestingTNewStorageIface interface {
	mock.TestingT
	Cleanup(func())
}

// NewStorageIface creates a new instance of StorageIface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStorageIface(t mockConstructorTestingTNewStorageIface) *StorageIface {
	mock := &StorageIface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
