// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: proto/server.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{0}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{1}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MetricRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mtype string                 `protobuf:"bytes,2,opt,name=mtype,proto3" json:"mtype,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*MetricRequest_GaugeValue
	//	*MetricRequest_CounterDelta
	Value         isMetricRequest_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	mi := &file_proto_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{3}
}

func (x *MetricRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetricRequest) GetMtype() string {
	if x != nil {
		return x.Mtype
	}
	return ""
}

func (x *MetricRequest) GetValue() isMetricRequest_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MetricRequest) GetGaugeValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*MetricRequest_GaugeValue); ok {
			return x.GaugeValue
		}
	}
	return 0
}

func (x *MetricRequest) GetCounterDelta() int64 {
	if x != nil {
		if x, ok := x.Value.(*MetricRequest_CounterDelta); ok {
			return x.CounterDelta
		}
	}
	return 0
}

type isMetricRequest_Value interface {
	isMetricRequest_Value()
}

type MetricRequest_GaugeValue struct {
	GaugeValue float64 `protobuf:"fixed64,3,opt,name=gauge_value,json=gaugeValue,proto3,oneof"`
}

type MetricRequest_CounterDelta struct {
	CounterDelta int64 `protobuf:"varint,4,opt,name=counter_delta,json=counterDelta,proto3,oneof"`
}

func (*MetricRequest_GaugeValue) isMetricRequest_Value() {}

func (*MetricRequest_CounterDelta) isMetricRequest_Value() {}

type GetMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mtype         string                 `protobuf:"bytes,2,opt,name=mtype,proto3" json:"mtype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricRequest) Reset() {
	*x = GetMetricRequest{}
	mi := &file_proto_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricRequest) ProtoMessage() {}

func (x *GetMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricRequest.ProtoReflect.Descriptor instead.
func (*GetMetricRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{4}
}

func (x *GetMetricRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMetricRequest) GetMtype() string {
	if x != nil {
		return x.Mtype
	}
	return ""
}

type MetricResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mtype string                 `protobuf:"bytes,2,opt,name=mtype,proto3" json:"mtype,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*MetricResponse_GaugeValue
	//	*MetricResponse_CounterDelta
	Value         isMetricResponse_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricResponse) Reset() {
	*x = MetricResponse{}
	mi := &file_proto_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricResponse) ProtoMessage() {}

func (x *MetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricResponse.ProtoReflect.Descriptor instead.
func (*MetricResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{5}
}

func (x *MetricResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetricResponse) GetMtype() string {
	if x != nil {
		return x.Mtype
	}
	return ""
}

func (x *MetricResponse) GetValue() isMetricResponse_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MetricResponse) GetGaugeValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*MetricResponse_GaugeValue); ok {
			return x.GaugeValue
		}
	}
	return 0
}

func (x *MetricResponse) GetCounterDelta() int64 {
	if x != nil {
		if x, ok := x.Value.(*MetricResponse_CounterDelta); ok {
			return x.CounterDelta
		}
	}
	return 0
}

type isMetricResponse_Value interface {
	isMetricResponse_Value()
}

type MetricResponse_GaugeValue struct {
	GaugeValue float64 `protobuf:"fixed64,3,opt,name=gauge_value,json=gaugeValue,proto3,oneof"`
}

type MetricResponse_CounterDelta struct {
	CounterDelta int64 `protobuf:"varint,4,opt,name=counter_delta,json=counterDelta,proto3,oneof"`
}

func (*MetricResponse_GaugeValue) isMetricResponse_Value() {}

func (*MetricResponse_CounterDelta) isMetricResponse_Value() {}

type MetricsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*MetricRequest       `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsListRequest) Reset() {
	*x = MetricsListRequest{}
	mi := &file_proto_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsListRequest) ProtoMessage() {}

func (x *MetricsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsListRequest.ProtoReflect.Descriptor instead.
func (*MetricsListRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{6}
}

func (x *MetricsListRequest) GetMetrics() []*MetricRequest {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetricsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*MetricResponse      `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsListResponse) Reset() {
	*x = MetricsListResponse{}
	mi := &file_proto_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsListResponse) ProtoMessage() {}

func (x *MetricsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsListResponse.ProtoReflect.Descriptor instead.
func (*MetricsListResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{7}
}

func (x *MetricsListResponse) GetMetrics() []*MetricResponse {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_proto_server_proto protoreflect.FileDescriptor

const file_proto_server_proto_rawDesc = "" +
	"\n" +
	"\x12proto/server.proto\x12\x06server\"\a\n" +
	"\x05Empty\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x88\x01\n" +
	"\rMetricRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05mtype\x18\x02 \x01(\tR\x05mtype\x12!\n" +
	"\vgauge_value\x18\x03 \x01(\x01H\x00R\n" +
	"gaugeValue\x12%\n" +
	"\rcounter_delta\x18\x04 \x01(\x03H\x00R\fcounterDeltaB\a\n" +
	"\x05value\"8\n" +
	"\x10GetMetricRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05mtype\x18\x02 \x01(\tR\x05mtype\"\x89\x01\n" +
	"\x0eMetricResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05mtype\x18\x02 \x01(\tR\x05mtype\x12!\n" +
	"\vgauge_value\x18\x03 \x01(\x01H\x00R\n" +
	"gaugeValue\x12%\n" +
	"\rcounter_delta\x18\x04 \x01(\x03H\x00R\fcounterDeltaB\a\n" +
	"\x05value\"E\n" +
	"\x12MetricsListRequest\x12/\n" +
	"\ametrics\x18\x01 \x03(\v2\x15.server.MetricRequestR\ametrics\"G\n" +
	"\x13MetricsListResponse\x120\n" +
	"\ametrics\x18\x01 \x03(\v2\x16.server.MetricResponseR\ametrics2\xcf\x02\n" +
	"\x0eMetricsService\x12?\n" +
	"\fUpdateMetric\x12\x15.server.MetricRequest\x1a\x16.server.MetricResponse\"\x00\x12?\n" +
	"\tGetMetric\x12\x18.server.GetMetricRequest\x1a\x16.server.MetricResponse\"\x00\x12J\n" +
	"\rUpdateMetrics\x12\x1a.server.MetricsListRequest\x1a\x1b.server.MetricsListResponse\"\x00\x123\n" +
	"\x04Ping\x12\x13.server.PingRequest\x1a\x14.server.PingResponse\"\x00\x12:\n" +
	"\n" +
	"GetMetrics\x12\r.server.Empty\x1a\x1b.server.MetricsListResponse\"\x00B)Z'github.com/runtime-metrics-course/protob\x06proto3"

var (
	file_proto_server_proto_rawDescOnce sync.Once
	file_proto_server_proto_rawDescData []byte
)

func file_proto_server_proto_rawDescGZIP() []byte {
	file_proto_server_proto_rawDescOnce.Do(func() {
		file_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_server_proto_rawDesc), len(file_proto_server_proto_rawDesc)))
	})
	return file_proto_server_proto_rawDescData
}

var file_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_server_proto_goTypes = []any{
	(*Empty)(nil),               // 0: server.Empty
	(*PingRequest)(nil),         // 1: server.PingRequest
	(*PingResponse)(nil),        // 2: server.PingResponse
	(*MetricRequest)(nil),       // 3: server.MetricRequest
	(*GetMetricRequest)(nil),    // 4: server.GetMetricRequest
	(*MetricResponse)(nil),      // 5: server.MetricResponse
	(*MetricsListRequest)(nil),  // 6: server.MetricsListRequest
	(*MetricsListResponse)(nil), // 7: server.MetricsListResponse
}
var file_proto_server_proto_depIdxs = []int32{
	3, // 0: server.MetricsListRequest.metrics:type_name -> server.MetricRequest
	5, // 1: server.MetricsListResponse.metrics:type_name -> server.MetricResponse
	3, // 2: server.MetricsService.UpdateMetric:input_type -> server.MetricRequest
	4, // 3: server.MetricsService.GetMetric:input_type -> server.GetMetricRequest
	6, // 4: server.MetricsService.UpdateMetrics:input_type -> server.MetricsListRequest
	1, // 5: server.MetricsService.Ping:input_type -> server.PingRequest
	0, // 6: server.MetricsService.GetMetrics:input_type -> server.Empty
	5, // 7: server.MetricsService.UpdateMetric:output_type -> server.MetricResponse
	5, // 8: server.MetricsService.GetMetric:output_type -> server.MetricResponse
	7, // 9: server.MetricsService.UpdateMetrics:output_type -> server.MetricsListResponse
	2, // 10: server.MetricsService.Ping:output_type -> server.PingResponse
	7, // 11: server.MetricsService.GetMetrics:output_type -> server.MetricsListResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_server_proto_init() }
func file_proto_server_proto_init() {
	if File_proto_server_proto != nil {
		return
	}
	file_proto_server_proto_msgTypes[3].OneofWrappers = []any{
		(*MetricRequest_GaugeValue)(nil),
		(*MetricRequest_CounterDelta)(nil),
	}
	file_proto_server_proto_msgTypes[5].OneofWrappers = []any{
		(*MetricResponse_GaugeValue)(nil),
		(*MetricResponse_CounterDelta)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_server_proto_rawDesc), len(file_proto_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_server_proto_goTypes,
		DependencyIndexes: file_proto_server_proto_depIdxs,
		MessageInfos:      file_proto_server_proto_msgTypes,
	}.Build()
	File_proto_server_proto = out.File
	file_proto_server_proto_goTypes = nil
	file_proto_server_proto_depIdxs = nil
}
